### ISSUE TITLE
Untalented | Gatekeeping

### ISSUE THREAD

**Issue by clipssender31** [Abo3abd1/Tellonym-Generator#1]
Stop gatekeeping such a simple tool xd

Free: https://github.com/clipssender31/Tellonym.me-Account-Creator

**Comment by Abo3abd1** [comment]
i have no idea about this project, mine 100% built by me, and its basic tool not like you've mentioned, and the reason i wont release it cuz i dont want to get into illegal troubles, thanks.

**Comment by clipssender31** [comment]
"illegal troubles" 🤓 You're untalented and a little kid.
